import {
  UmojaLinnConsultation,
  UmojaLinnConsultationAvailability,
  UmojaLinnAvailableTimeslot,
} from "@/types/consultation";

// ─── Shared mock participants ────────────────────────────────────────────────

const mockBuyer = {
  id: "buyer-001",
  firstName: "Alex",
  lastName: "Johnson",
  profilePhotoUri: null,
  tag: "alex.johnson",
  about: null,
  location: "Lagos, Nigeria",
  totalEarnings: null,
  totalJobs: null,
  successRate: null,
  averageRating: null,
  specialistType: null,
  brandName: null,
  summaryAcceptanceRate: null,
};

const mockDesigner = {
  id: "designer-001",
  firstName: "Samuel",
  lastName: "Alex",
  profilePhotoUri: null,
  tag: "samuel.alex",
  about:
    "I am a passionate fashion designer with 12 years of experience in the industry. My design aesthetic is a blend of classic elegance and contemporary flair, with an emphasis on creating pieces that are both beautiful and functional.",
  location: "Lagos, Port Harcourt",
  totalEarnings: 5000,
  totalJobs: 16,
  successRate: 100,
  averageRating: 3.0,
  specialistType: "Fashion Design",
  brandName: "Samuel Alex Studios",
  summaryAcceptanceRate: 85,
};

const mockProject = {
  id: "project-001",
  title: "My Wedding",
  description:
    "A-line dress with a sweetheart neckline and cap sleeves. The dress should be made from a light blue chiffon fabric, with a satin lining for a comfortable fit. I would like the bodice to be fitted and embroidered with delicate floral lace, and the skirt to be flowing and slightly gathered at the waist",
  budget: { min: 10, max: 200 },
  currency: "USD" as const,
  timeline: { startDate: "2025-01-25", endDate: "2025-01-30" },
  deliveryCountry: "United States",
  gender: "MALE" as const,
  inspirationImages: [
    "/mock/inspiration-1.jpg",
    "/mock/inspiration-2.jpg",
    "/mock/inspiration-3.jpg",
    "/mock/inspiration-4.jpg",
    "/mock/inspiration-5.jpg",
  ],
  clothingType: "Agbada",
  additionalNotes:
    "A-line dress with a sweetheart neckline and cap sleeves. The dress should be made from a light blue chiffon fabric.",
};

const mockSlot = {
  date: "2025-01-25",
  startTime: "10:30",
  endTime: "11:00",
  durationMins: 30 as const,
  timezone: "UTC",
};

const mockEscrow = {
  status: "FUNDED" as const,
  amount: 25000,
  currency: "NAIRA" as const,
  heldAmount: 25000,
  releasedAmount: 0,
};

const timestamps = {
  createdAt: "2025-01-20T10:00:00.000Z",
  updatedAt: "2025-01-20T10:00:00.000Z",
};

// ─── Buyer consultation mocks ────────────────────────────────────────────────

export const MOCK_BUYER_CONSULTATIONS: UmojaLinnConsultation[] = [
  // 1. Matching
  {
    id: "consult-matching-001",
    journey: "BUYER_GENERAL_REQUEST",
    buyerStatus: "MATCHING",
    designerStatus: "ASSIGNED",
    bookedSubStatus: null,
    completedSubStatus: null,
    isCancelled: false,
    buyer: mockBuyer,
    designer: null,
    consultationFee: null,
    currency: "USD",
    paymentProcessingFee: null,
    totalFee: null,
    project: mockProject,
    slot: null,
    escrow: null,
    summary: null,
    chatChannelId: null,
    rescheduleRequest: null,
    invoiceUrl: null,
    cancellationReason: null,
    cancelledBy: null,
    refundedAmount: null,
    hasOpenDispute: false,
    disputeRaisedBy: null,
    ...timestamps,
  },
  // 2. Matched
  {
    id: "consult-matched-001",
    journey: "BUYER_GENERAL_REQUEST",
    buyerStatus: "MATCHED",
    designerStatus: "ASSIGNED",
    bookedSubStatus: null,
    completedSubStatus: null,
    isCancelled: false,
    buyer: mockBuyer,
    designer: mockDesigner,
    consultationFee: 5,
    currency: "USD",
    paymentProcessingFee: 0.5,
    totalFee: 5.5,
    project: mockProject,
    slot: null,
    escrow: null,
    summary: null,
    chatChannelId: null,
    rescheduleRequest: null,
    invoiceUrl: null,
    cancellationReason: null,
    cancelledBy: null,
    refundedAmount: null,
    hasOpenDispute: false,
    disputeRaisedBy: null,
    ...timestamps,
  },
  // 3. Requested (designer sent request to buyer)
  {
    id: "consult-requested-001",
    journey: "DESIGNER_REQUEST",
    buyerStatus: "REQUESTED",
    designerStatus: "REQUESTED",
    bookedSubStatus: null,
    completedSubStatus: null,
    isCancelled: false,
    buyer: mockBuyer,
    designer: mockDesigner,
    consultationFee: 5,
    currency: "USD",
    paymentProcessingFee: 0.5,
    totalFee: 5.5,
    project: mockProject,
    slot: null,
    escrow: null,
    summary: null,
    chatChannelId: null,
    rescheduleRequest: null,
    invoiceUrl: null,
    cancellationReason: null,
    cancelledBy: null,
    refundedAmount: null,
    hasOpenDispute: false,
    disputeRaisedBy: null,
    ...timestamps,
  },
  // 4. Booked
  {
    id: "consult-booked-001",
    journey: "BUYER_GENERAL_REQUEST",
    buyerStatus: "BOOKED",
    designerStatus: "BOOKED",
    bookedSubStatus: "BOOKED",
    completedSubStatus: null,
    isCancelled: false,
    buyer: mockBuyer,
    designer: mockDesigner,
    consultationFee: 5,
    currency: "USD",
    paymentProcessingFee: 0.5,
    totalFee: 5.5,
    project: mockProject,
    slot: mockSlot,
    escrow: mockEscrow,
    summary: null,
    chatChannelId: "chat-booked-001",
    rescheduleRequest: null,
    invoiceUrl: "/mock/invoice.pdf",
    cancellationReason: null,
    cancelledBy: null,
    refundedAmount: null,
    hasOpenDispute: false,
    disputeRaisedBy: null,
    ...timestamps,
  },
  // 5. Booked — reschedule requested by designer
  {
    id: "consult-booked-reschedule-001",
    journey: "BUYER_GENERAL_REQUEST",
    buyerStatus: "BOOKED",
    designerStatus: "BOOKED",
    bookedSubStatus: "RESCHEDULE_REQUESTED",
    completedSubStatus: null,
    isCancelled: false,
    buyer: mockBuyer,
    designer: mockDesigner,
    consultationFee: 5,
    currency: "USD",
    paymentProcessingFee: 0.5,
    totalFee: 5.5,
    project: mockProject,
    slot: mockSlot,
    escrow: mockEscrow,
    summary: null,
    chatChannelId: "chat-booked-002",
    rescheduleRequest: {
      id: "reschedule-001",
      proposedSlot: {
        date: "2025-01-28",
        startTime: "14:00",
        endTime: "14:30",
        durationMins: 30,
        timezone: "UTC",
      },
      message: "I have a conflict at the original time, can we move?",
      proposedBy: "DESIGNER",
      status: "PENDING",
      proposedAt: "2025-01-22T09:00:00.000Z",
    },
    invoiceUrl: "/mock/invoice.pdf",
    cancellationReason: null,
    cancelledBy: null,
    refundedAmount: null,
    hasOpenDispute: false,
    disputeRaisedBy: null,
    ...timestamps,
  },
  // 6. Booked — missed by both parties
  {
    id: "consult-booked-noshow-001",
    journey: "BUYER_GENERAL_REQUEST",
    buyerStatus: "BOOKED",
    designerStatus: "BOOKED",
    bookedSubStatus: "NO_SHOW",
    completedSubStatus: null,
    isCancelled: false,
    buyer: mockBuyer,
    designer: mockDesigner,
    consultationFee: 5,
    currency: "USD",
    paymentProcessingFee: 0.5,
    totalFee: 5.5,
    project: mockProject,
    slot: { ...mockSlot, date: "2025-01-10" },
    escrow: mockEscrow,
    summary: null,
    chatChannelId: "chat-booked-003",
    rescheduleRequest: null,
    invoiceUrl: "/mock/invoice.pdf",
    cancellationReason: null,
    cancelledBy: null,
    refundedAmount: null,
    hasOpenDispute: false,
    disputeRaisedBy: "SYSTEM",
    ...timestamps,
  },
  // 7. Live
  {
    id: "consult-live-001",
    journey: "BUYER_GENERAL_REQUEST",
    buyerStatus: "LIVE",
    designerStatus: "LIVE",
    bookedSubStatus: null,
    completedSubStatus: null,
    isCancelled: false,
    buyer: mockBuyer,
    designer: mockDesigner,
    consultationFee: 5,
    currency: "USD",
    paymentProcessingFee: 0.5,
    totalFee: 5.5,
    project: mockProject,
    slot: { ...mockSlot, date: "2025-01-25", startTime: "10:00", endTime: "10:30" },
    escrow: mockEscrow,
    summary: null,
    chatChannelId: "chat-live-001",
    rescheduleRequest: null,
    invoiceUrl: "/mock/invoice.pdf",
    cancellationReason: null,
    cancelledBy: null,
    refundedAmount: null,
    hasOpenDispute: false,
    disputeRaisedBy: null,
    ...timestamps,
  },
  // 8. Live — with open dispute
  {
    id: "consult-live-dispute-001",
    journey: "BUYER_GENERAL_REQUEST",
    buyerStatus: "LIVE",
    designerStatus: "LIVE",
    bookedSubStatus: null,
    completedSubStatus: null,
    isCancelled: false,
    buyer: mockBuyer,
    designer: mockDesigner,
    consultationFee: 5,
    currency: "USD",
    paymentProcessingFee: 0.5,
    totalFee: 5.5,
    project: mockProject,
    slot: mockSlot,
    escrow: { ...mockEscrow, status: "HELD" },
    summary: null,
    chatChannelId: "chat-live-002",
    rescheduleRequest: null,
    invoiceUrl: "/mock/invoice.pdf",
    cancellationReason: null,
    cancelledBy: null,
    refundedAmount: null,
    hasOpenDispute: true,
    disputeRaisedBy: "BUYER",
    ...timestamps,
  },
  // 9. Completed — Awaiting summary
  {
    id: "consult-completed-awaiting-001",
    journey: "BUYER_GENERAL_REQUEST",
    buyerStatus: "COMPLETED",
    designerStatus: "AWAITING_SUMMARY",
    bookedSubStatus: null,
    completedSubStatus: "AWAITING_SUMMARY",
    isCancelled: false,
    buyer: mockBuyer,
    designer: mockDesigner,
    consultationFee: 5,
    currency: "USD",
    paymentProcessingFee: 0.5,
    totalFee: 5.5,
    project: mockProject,
    slot: mockSlot,
    escrow: { ...mockEscrow, status: "RELEASED", releasedAmount: 25000, heldAmount: 0 },
    summary: {
      id: "summary-001",
      docUrl: null,
      docName: null,
      docSizeKb: null,
      status: "AWAITING",
      submittedAt: null,
      reviewedAt: null,
      rejectionReason: null,
      ...timestamps,
    },
    chatChannelId: "chat-completed-001",
    rescheduleRequest: null,
    invoiceUrl: "/mock/invoice.pdf",
    cancellationReason: null,
    cancelledBy: null,
    refundedAmount: null,
    hasOpenDispute: false,
    disputeRaisedBy: null,
    ...timestamps,
  },
  // 10. Completed — Summary submitted
  {
    id: "consult-completed-submitted-001",
    journey: "BUYER_GENERAL_REQUEST",
    buyerStatus: "COMPLETED",
    designerStatus: "COMPLETED",
    bookedSubStatus: null,
    completedSubStatus: "SUMMARY_SUBMITTED",
    isCancelled: false,
    buyer: mockBuyer,
    designer: mockDesigner,
    consultationFee: 5,
    currency: "USD",
    paymentProcessingFee: 0.5,
    totalFee: 5.5,
    project: mockProject,
    slot: mockSlot,
    escrow: { ...mockEscrow, status: "RELEASED", releasedAmount: 25000, heldAmount: 0 },
    summary: {
      id: "summary-002",
      docUrl: "/mock/summary.pdf",
      docName: "Consultation Summary.pdf",
      docSizeKb: 200,
      status: "SUBMITTED",
      submittedAt: "2025-01-26T10:00:00.000Z",
      reviewedAt: null,
      rejectionReason: null,
      ...timestamps,
    },
    chatChannelId: "chat-completed-002",
    rescheduleRequest: null,
    invoiceUrl: "/mock/invoice.pdf",
    cancellationReason: null,
    cancelledBy: null,
    refundedAmount: null,
    hasOpenDispute: false,
    disputeRaisedBy: null,
    ...timestamps,
  },
  // 11. Completed — Summary accepted (book another)
  {
    id: "consult-completed-accepted-001",
    journey: "BUYER_GENERAL_REQUEST",
    buyerStatus: "COMPLETED",
    designerStatus: "COMPLETED",
    bookedSubStatus: null,
    completedSubStatus: "SUMMARY_ACCEPTED",
    isCancelled: false,
    buyer: mockBuyer,
    designer: mockDesigner,
    consultationFee: 5,
    currency: "USD",
    paymentProcessingFee: 0.5,
    totalFee: 5.5,
    project: mockProject,
    slot: mockSlot,
    escrow: { ...mockEscrow, status: "RELEASED", releasedAmount: 25000, heldAmount: 0 },
    summary: {
      id: "summary-003",
      docUrl: "/mock/summary.pdf",
      docName: "Consultation Summary.pdf",
      docSizeKb: 200,
      status: "ACCEPTED",
      submittedAt: "2025-01-26T10:00:00.000Z",
      reviewedAt: "2025-01-27T10:00:00.000Z",
      rejectionReason: null,
      ...timestamps,
    },
    chatChannelId: "chat-completed-003",
    rescheduleRequest: null,
    invoiceUrl: "/mock/invoice.pdf",
    cancellationReason: null,
    cancelledBy: null,
    refundedAmount: null,
    hasOpenDispute: false,
    disputeRaisedBy: null,
    ...timestamps,
  },
  // 12. Completed — with dispute
  {
    id: "consult-completed-dispute-001",
    journey: "BUYER_GENERAL_REQUEST",
    buyerStatus: "COMPLETED",
    designerStatus: "COMPLETED",
    bookedSubStatus: null,
    completedSubStatus: "DISPUTE",
    isCancelled: false,
    buyer: mockBuyer,
    designer: mockDesigner,
    consultationFee: 5,
    currency: "USD",
    paymentProcessingFee: 0.5,
    totalFee: 5.5,
    project: mockProject,
    slot: mockSlot,
    escrow: { ...mockEscrow, status: "HELD" },
    summary: null,
    chatChannelId: "chat-completed-004",
    rescheduleRequest: null,
    invoiceUrl: "/mock/invoice.pdf",
    cancellationReason: null,
    cancelledBy: null,
    refundedAmount: null,
    hasOpenDispute: true,
    disputeRaisedBy: "BUYER",
    ...timestamps,
  },
  // 13. Cancelled — designer cancelled
  {
    id: "consult-cancelled-designer-001",
    journey: "BUYER_GENERAL_REQUEST",
    buyerStatus: "CANCELLED",
    designerStatus: "CANCELLED",
    bookedSubStatus: null,
    completedSubStatus: null,
    isCancelled: true,
    buyer: mockBuyer,
    designer: mockDesigner,
    consultationFee: 5,
    currency: "USD",
    paymentProcessingFee: 0.5,
    totalFee: 5.5,
    project: mockProject,
    slot: mockSlot,
    escrow: { ...mockEscrow, status: "REFUNDED", releasedAmount: 0, heldAmount: 0 },
    summary: null,
    chatChannelId: null,
    rescheduleRequest: null,
    invoiceUrl: null,
    cancellationReason: "Designer cancelled",
    cancelledBy: "DESIGNER",
    refundedAmount: 25000,
    hasOpenDispute: false,
    disputeRaisedBy: null,
    ...timestamps,
  },
  // 14. Cancelled — no payment taken
  {
    id: "consult-cancelled-nopay-001",
    journey: "BUYER_GENERAL_REQUEST",
    buyerStatus: "CANCELLED",
    designerStatus: "CANCELLED",
    bookedSubStatus: null,
    completedSubStatus: null,
    isCancelled: true,
    buyer: mockBuyer,
    designer: mockDesigner,
    consultationFee: 5,
    currency: "USD",
    paymentProcessingFee: 0.5,
    totalFee: 5.5,
    project: mockProject,
    slot: null,
    escrow: null,
    summary: null,
    chatChannelId: null,
    rescheduleRequest: null,
    invoiceUrl: null,
    cancellationReason: "Buyer cancelled before booking",
    cancelledBy: "BUYER",
    refundedAmount: null,
    hasOpenDispute: false,
    disputeRaisedBy: null,
    ...timestamps,
  },
];

// ─── Designer consultation mocks (reuse buyer list, different statuses) ───────

export const MOCK_DESIGNER_CONSULTATIONS: UmojaLinnConsultation[] =
  MOCK_BUYER_CONSULTATIONS.map((c) => ({ ...c }));

// ─── Designer availability mock ───────────────────────────────────────────────

export const MOCK_DESIGNER_AVAILABILITY: UmojaLinnConsultationAvailability = {
  id: "availability-001",
  designerId: "designer-001",
  isAvailableForConsultation: true,
  timezone: "UTC",
  slots: [
    { day: "MONDAY", from: "09:00", to: "17:00", isAvailable: true },
    { day: "TUESDAY", from: "09:00", to: "17:00", isAvailable: true },
    { day: "WEDNESDAY", from: "09:00", to: "17:00", isAvailable: true },
    { day: "THURSDAY", from: "09:00", to: "17:00", isAvailable: true },
    { day: "FRIDAY", from: "09:00", to: "15:00", isAvailable: true },
    { day: "SATURDAY", from: "10:00", to: "13:00", isAvailable: false },
    { day: "SUNDAY", from: "10:00", to: "13:00", isAvailable: false },
  ],
  durations: [
    { durationMins: 30, price: 5, currency: "USD", isEnabled: true },
    { durationMins: 45, price: 8, currency: "USD", isEnabled: true },
    { durationMins: 60, price: 10, currency: "USD", isEnabled: false },
  ],
  bufferMinsBetweenSessions: 15,
  advanceBookingDays: 14,
  ...timestamps,
};

// ─── Available timeslots mock (for booking calendar) ─────────────────────────

export const MOCK_AVAILABLE_TIMESLOTS: UmojaLinnAvailableTimeslot[] = [
  {
    date: "2025-01-27",
    slots: [
      { startTime: "09:00", endTime: "09:30", durationMins: 30 },
      { startTime: "10:00", endTime: "10:30", durationMins: 30 },
      { startTime: "11:00", endTime: "11:30", durationMins: 30 },
      { startTime: "14:00", endTime: "14:30", durationMins: 30 },
    ],
  },
  {
    date: "2025-01-28",
    slots: [
      { startTime: "09:00", endTime: "09:30", durationMins: 30 },
      { startTime: "10:30", endTime: "11:00", durationMins: 30 },
      { startTime: "13:00", endTime: "13:30", durationMins: 30 },
    ],
  },
  {
    date: "2025-01-29",
    slots: [
      { startTime: "10:00", endTime: "10:30", durationMins: 30 },
      { startTime: "15:00", endTime: "15:30", durationMins: 30 },
    ],
  },
  {
    date: "2025-01-30",
    slots: [
      { startTime: "09:00", endTime: "09:30", durationMins: 30 },
      { startTime: "11:00", endTime: "11:30", durationMins: 30 },
    ],
  },
  {
    date: "2025-01-31",
    slots: [
      { startTime: "10:00", endTime: "10:30", durationMins: 30 },
      { startTime: "14:00", endTime: "14:30", durationMins: 30 },
      { startTime: "16:00", endTime: "16:30", durationMins: 30 },
    ],
  },
];
