import type { Metadata } from "next";

import "./globals.css";
import "react-international-phone/style.css";

import { Inter } from "next/font/google";

const InterSans = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Welcome to Umoja",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className={`${InterSans.className}  antialiased`}>{children}</body>
    </html>
  );
}
