name: Pre-Commit Checks

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Run Lint
        run: yarn lint

      - name: Run Type Check
        run: yarn type-check

      - name: Create .env file at runtime
        run: |
          # 1. Clear any existing build-env file to prevent duplicates
          true > .env.production
          
          # 2. Extract and dump all GitHub Secrets into the file
          echo '${{ toJSON(secrets) }}' | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' >> .env.production
          
          # 3. Extract and append all GitHub Variables into the file
          echo '${{ toJSON(vars) }}' | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' >> .env.production

      - name: Run next build
        run: yarn build
